### ISSUE TITLE
add option to only inject selected pods

### ISSUE THREAD

**Issue by qrkourier** [netfoundry/ziti-k8s-agent#13]
Presently, all pods in the selected namespace have sidecars injected. It's necessary to have an option to limit injection to selected pods in selected namespaces.

This can be a webhook option, hopefully. For example, the default mode could be "all pods in selected namespace(s)" with the option to inject "selected pod(s) in selected namespace(s).

**Comment by dariuszSki** [comment]
ok, we can add an option for users to pass a pod label that the injector can look for. If both the namespace and pod labels overlap, then the namespace label would take precedence?

**Comment by qrkourier** [comment]
Currently, all pods in a namespace selected by label `openziti/ziti-tunnel=enabled`. What if we used this label instead to set a mode?

For example,

- `openziti/ziti-tunnel=enabled` currently means "all pods in this namespace"

We could preserve that behavior by allowing another value `openziti/ziti-tunnel=annotated`, meaning "only pods with an identity role annotation."

This seems acceptable, but I would prefer something else. I'm continuing to generate ideas.

**Comment by dariuszSki** [comment]
Yeah, lets continue to hash this out. Great points, if same label, then ?openziti/ziti-tunnel=namespace , openziti/ziti-tunnel=pod,'
would one want entire namespace1 but few pods in namespace2 for example?
